import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import AuthShowCase from "~/components/AuthShowCase";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Little alchemy - Clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="https://littlealchemy.com/img/little-alchemy-1024-logo.png" />
      </Head>

      <main data-theme="light" className="min-h-screen">
        <div className="w-full h-full">
          <div className="flex justify-center mx-auto py-5">
            <div className="flex flex-col justify-center gap-8">
              <img className="h-32" src="/logoApp.png" alt="logo" />
              <Link className="w-full" href={'/main'}>
                <button className="w-full h-28 btn btn-outline bg-[rgb(189,47,168)] text-5xl text-white py-6 text-center">PLAY</button>
              </Link>
            </div>
          </div>

          <div className="flex flex-col items-center gap-2">
            <AuthShowCase />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;